apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    # Secret with AWS credentials based on credentials.txt file format
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
